version: "3"

services:
  backend:
    container_name: backend
    build:
      context: "./backend"
      dockerfile: deploy/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/backend/gcloud_key.json
      - PROJECT_ID=github-334619
      - DOCKER=True

  frontend:
    container_name: frontend
    build:
      context: "./frontend"
      dockerfile: deploy/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
